create table bear
(
    id          int generated by default as identity,
    name        varchar(255) NOT NULL,
    description text         NOT NULL,
    cost        int          NOT NULL,
    img_link    varchar(255) NOT NULL
);

insert into bear(name, description, cost, img_link)
VALUES ('Вишневая Семёрка',
        E'Легкое фруктовое пиво с ярким насыщенным вишневым вкусом и ароматом.' ||
        E'\nЛегкая освежающая кислинка продолжает тему сладкой вишни.' ||
        E'\nЛинейка сорта: Леса, сады и огороды',
        290,
        'https://www.dropbox.com/scl/fi/vbzxgs62im85k6xdlb9gj/3.jpg?rlkey=dsd3po13efrun1l5d9y8xdkfi&st=1fgdym4y&raw=1');

insert into bear(name, description, cost, img_link)
VALUES ('Парень на девятке',
        E'Это светлое, умеренно крепкое пиво, которое хорошо освежает за счет гармоничного сочетания цитрусовых оттенков вкуса и очень деликатных хмелевых ноток. ' ||
        E'\nНеповторимый вкус сформирован сочетанием пшеничных и ячменных солодовых тонов, специальным сортом дрожжей, двумя немецкими сортами хмеля.' ||
        E'\nСтиль: Витбир',
        260,
        'https://www.dropbox.com/scl/fi/2zqqoghwn4vrlmqgz0q7m/2.jpg?rlkey=w338m0nk8jakgqpb52cwvueos&st=1blgwpzc&raw=1');


insert into bear(name, description, cost, img_link)
VALUES ('Боевая копейка',
        E'Это классический эль, настолько классический, как и авто, в честь которого и названо пиво.' ||
        E'\nВ меру крепкое, имеет хорошую горечь, такую же, как и после очередной поломки всеми любимой «копейки».',
        270,
        'https://www.dropbox.com/scl/fi/fj7gujjesc8ozk16843a3/4.jpg?rlkey=p4yqpiiuhflpvrwgy3z9l3g8s&st=dspjvjso&raw=1');


insert into bear(name, description, cost, img_link)
VALUES ('Гаражные истории',
        E'Темный пшеничный лагер, очень крепкий, как руки тех ребят, что пьют его, рассказывая свои истории о темном прошлом и тюнингуя свою любимую ласточку.' ||
        E'\nВ вкусовой палитре данного напитка присутствуют нотки карамели и цитрусовых, но на вкус больше похоже на старый добрый квас из бочонка.',
        330,
        'https://www.dropbox.com/scl/fi/k81sv82cwrvkvex1rh0qg/5.jpg?rlkey=6nsh37kc3netimg01pqhj7zbh&st=3d92u84t&raw=1');


insert into bear(name, description, cost, img_link)
VALUES ('Streets Moments',
        E'Это напиток, который сочетает в себе мёд, перечную мяту, солод и хмель. ' ||
        E'\nЕго вкус — насыщенный и бодрящий, он надолго останется в памяти, как и ночные гонки до рассвета в компании самых близких людей.',
        340,
        'https://www.dropbox.com/scl/fi/54814ypn91xa95thr1lq6/6.jpg?rlkey=tr8az35aewvyu3qrtbxvjxxpd&st=g6jwjim3&raw=1');


insert into bear(name, description, cost, img_link)
VALUES ('LTAC — Легенда Тайм Атак',
        E'Погрузитесь в мир адреналина и скорости с LTAC — пивом, созданным для настоящих гонщиков.' ||
        E'\nЭтот сорт обладает ярким, насыщенным вкусом, который напоминает о ревущих моторах и резких поворотах на извивающихся трассах.',
        250,
        'https://www.dropbox.com/scl/fi/e0ud13fvfqunrhocp5e18/7.jpg?rlkey=5f2y5cocw2p8rrq3506v86vow&st=u3jcxw6z&raw=1');